<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="K4os.Compression.LZ4" Version="1.3.8" />
    <PackageReference Include="K4os.Compression.LZ4.Streams" Version="1.3.8" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MonoGame.Framework">
      <HintPath>F:\steam\steamapps\common\Stardew Valley\MonoGame.Framework.dll</HintPath>
    </Reference>
    <Reference Include="xTile">
      <HintPath>F:\steam\steamapps\common\Stardew Valley\xTile.dll</HintPath>
    </Reference>
    <Reference Include="StardewValley.GameData">
      <HintPath>F:\steam\steamapps\common\Stardew Valley\StardewValley.GameData.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
